/**
 * ATM - Skill Loader 生成模块
 * 生成 generated_skill_loader.il 文件，按依赖关系排序
 */
import path from 'path';
import { ATM_SKILL_LOADER_START, ATM_SKILL_LOADER_END } from '../../src/types/skill';
import type { ScannedSkill } from '../../src/types/skill';

/**
 * 拓扑排序 - 按 package.json requires 字段排序 Skill
 * 无依赖或依赖已满足的排前面
 *
 * @param skills Skill 列表（将修改排序）
 * @returns 排序后的 Skill 列表
 */
export function topologicalSortSkills(skills: ScannedSkill[]): ScannedSkill[] {
  const sorted: ScannedSkill[] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();

  // 构建名称 → Skill 映射
  const skillMap = new Map<string, ScannedSkill>();
  for (const skill of skills) {
    skillMap.set(skill.name.toLowerCase(), skill);
  }

  function visit(skill: ScannedSkill): void {
    const key = skill.name.toLowerCase();
    if (visited.has(key)) return;
    if (visiting.has(key)) {
      // 循环依赖，跳过
      return;
    }

    visiting.add(key);

    // 先访问依赖
    if (skill.hasPackageJson && skill.dependencies.length > 0) {
      for (const depName of skill.dependencies) {
        const depSkill = skillMap.get(depName.toLowerCase());
        if (depSkill && !visited.has(depName.toLowerCase())) {
          visit(depSkill);
        }
      }
    }

    visiting.delete(key);
    visited.add(key);
    sorted.push(skill);
  }

  for (const skill of skills) {
    if (!visited.has(skill.name.toLowerCase())) {
      visit(skill);
    }
  }

  return sorted;
}

/**
 * 生成 generated_skill_loader.il 文件内容
 *
 * @param userSkills 用户 Skill 列表（仅已启用的）
 * @param atmSkills ATM Skill 列表（仅已启用的）
 * @param pcbenvPath pcbenv 目录路径（用于计算相对路径的正斜杠格式）
 * @returns 完整的 loader 文件内容
 */
export function generateSkillLoader(
  userSkills: ScannedSkill[],
  atmSkills: ScannedSkill[],
  pcbenvPath: string
): string {
  const lines: string[] = [];

  lines.push(ATM_SKILL_LOADER_START);
  lines.push('; Auto-generated by ATM - do not edit manually');
  lines.push(`; Generated: ${new Date().toISOString()}`);
  lines.push('');

  const normalizedPcbenv = pcbenvPath.replace(/\\/g, '/');

  // === 用户 Skill ===
  const enabledUserSkills = userSkills.filter((s) => s.status === 'enabled');
  const sortedUserSkills = topologicalSortSkills(enabledUserSkills);

  if (sortedUserSkills.length > 0) {
    lines.push('; === User Skills ===');
    for (const skill of sortedUserSkills) {
      const normalizedPath = skill.filePath.replace(/\\/g, '/');
      // 尝试使用相对路径，缩短长度
      const loadPath = normalizedPath;
      lines.push(`load("${loadPath}")`);
    }
    lines.push('');
  }

  // === ATM Skill ===
  const enabledAtmSkills = atmSkills.filter((s) => s.status === 'enabled');
  const sortedAtmSkills = topologicalSortSkills(enabledAtmSkills);

  if (sortedAtmSkills.length > 0) {
    lines.push('; === ATM Managed Skills ===');
    for (const skill of sortedAtmSkills) {
      const normalizedPath = skill.filePath.replace(/\\/g, '/');
      lines.push(`load("${normalizedPath}")`);
    }
    lines.push('');
  } else {
    lines.push('; === ATM Managed Skills ===');
    lines.push('; (none)');
    lines.push('');
  }

  // 注释说明
  lines.push('; Company skills are loaded via CDS_SITE/SKILL_PATH mechanism');
  lines.push('; and are not managed by ATM.');

  lines.push(ATM_SKILL_LOADER_END);
  lines.push('');

  return lines.join('\n');
}

/**
 * 根据快捷键的启用/禁用操作，生成新的 Skill 状态列表和重新生成 loader 的标识
 *
 * @param allSkills 全部 Skill
 * @param skillPath 要切换的 Skill 文件路径
 * @param newStatus 新状态
 * @returns 更新后的 Skill 列表
 */
export function updateSkillStatus(
  allSkills: ScannedSkill[],
  skillPath: string,
  newStatus: 'enabled' | 'disabled'
): ScannedSkill[] {
  return allSkills.map((s) => {
    if (s.filePath === skillPath) {
      // 公司 Skill 不可切换
      if (s.tier === 'company') return s;
      return { ...s, status: newStatus };
    }
    return s;
  });
}

/**
 * 检查切换操作是否需要重启 Allegro
 * 启用/禁用用户 Skill 通常需要重启才能生效
 */
export function skillToggleRequiresRestart(skill: ScannedSkill): boolean {
  return skill.tier === 'user' || skill.tier === 'atm';
}
