/**
 * ATM - Bootstrap 生成模块
 * 生成 ATM Bootstrap 加载链，从 generateManagedEnvBlock.ts 提取独立
 */
import { ATM_BOOTSTRAP_START, ATM_BOOTSTRAP_END } from '../../src/types/skill';

/**
 * 生成 ATM Bootstrap 插入内容
 * 现在除了加载 bootstrap.il，还会链式加载 generated_skill_loader.il
 *
 * @param atmGeneratedPath atm_generated 目录的路径（正斜杠格式）
 * @returns bootstrap 行
 */
export function generateBootstrapLines(atmGeneratedPath: string): string {
  // 确保路径使用正斜杠
  const normalizedPath = atmGeneratedPath.replace(/\\/g, '/');
  const bootstrapFilePath = `${normalizedPath}/bootstrap.il`;

  return [
    ATM_BOOTSTRAP_START,
    `load("${bootstrapFilePath}")`,
    ATM_BOOTSTRAP_END,
  ].join('\n');
}

/**
 * 生成 bootstrap.il 文件内容
 * bootstrap.il 是 ATM 生成的入口文件，负责加载 skill loader
 *
 * @param atmGeneratedPath atm_generated 目录路径
 * @returns bootstrap.il 的完整内容
 */
export function generateBootstrapIlContent(atmGeneratedPath: string): string {
  const normalizedPath = atmGeneratedPath.replace(/\\/g, '/');
  return [
    ';; ATM Bootstrap - Auto-generated by ATM',
    `;; Generated: ${new Date().toISOString()}`,
    ';;',
    ';; This file is auto-generated. Do not edit manually.',
    ';;',
    '',
    `load("${normalizedPath}/generated_skill_loader.il")`,
    '',
  ].join('\n');
}

/**
 * 检测 allegro.ilinit 中是否已有 ATM bootstrap
 * @param content ilinit 文件内容
 * @returns 是否已有 bootstrap
 */
export function hasBootstrapInIlinit(content: string): boolean {
  return (
    content.includes(ATM_BOOTSTRAP_START) &&
    content.includes(ATM_BOOTSTRAP_END)
  );
}

/**
 * 向 allegro.ilinit 插入 ATM bootstrap（如果还不存在）
 * @param currentContent 当前 ilinit 内容
 * @param bootstrapContent bootstrap 行（由 generateBootstrapLines 生成）
 * @returns 更新后的 ilinit 内容，或 null 如果已存在
 */
export function insertBootstrapToIlinit(
  currentContent: string,
  bootstrapContent: string
): string | null {
  if (hasBootstrapInIlinit(currentContent)) {
    return null; // 已存在，不重复插入
  }

  // 在文件末尾追加
  const trimmedContent = currentContent.endsWith('\n')
    ? currentContent
    : currentContent + '\n';

  // 如果文件不为空，加空行分隔
  const separator = currentContent.trim() ? '\n' : '';
  return trimmedContent + separator + bootstrapContent + '\n';
}
