/**
 * ATM - symphony_skill.txt 解析与生成模块
 *
 * Symphony（Team Design）下所有 SKILL 命令默认禁用，只有登记在
 * symphony_skill.txt 中的命令才被放行。文件格式（官方模板）：
 *
 *     command_name
 *     command_name   rw
 *     "command_name"
 *     "command name" rw
 *     "command name"    ; comment
 *
 * 要点：
 *   - 每行一个命令；多词命令必须加引号
 *   - 分号后为注释
 *   - 不带 rw 的命令视为只读：其数据库变更不会广播到 Symphony 服务器
 *   - 只有带 rw 的命令允许发送数据库更新
 */
import type {
  GenerateSymphonySkillOptions,
  SymphonyCommandEntry,
  SymphonySkillFileContent,
} from '../../src/types/symphony';

/** ATM 生成标记（用于识别 ATM 托管文件段） */
export const SYMPHONY_ATM_MARKER_START = '; ===== ATM Generated Symphony Skill File Start =====';
export const SYMPHONY_ATM_MARKER_END = '; ===== ATM Generated Symphony Skill File End =====';

/** 官方模板说明头部（生成新文件时使用） */
export const SYMPHONY_OFFICIAL_HEADER = [
  '; This file contains a list of SKILL commands enabled in multi-user',
  '; mode.  Only SKILL commands contained in this file will be allowed to',
  '; run when connected to the Symphony Server, all others will be forbidden.',
  ';',
  '; To add a command to this file, use one the following syntaxes:',
  ';',
  ';     command_name',
  ';     command_name   rw',
  ';     "command_name"',
  ';     "command name" rw',
  ';     "command name"    ; comment',
  ';     "command name" rw ; comment',
  ';',
  '; Only one command may be entered per line.',
  '; All multi-word command names must be surrounded by quotes.',
  '; Blank lines are ignored.',
  '; Text after a semicolon is ignored.',
  ';',
  '; Commands without the rw (read-write) flag are considered read-only and',
  '; database changes made by the command will not be sent to the Symphony Server.',
  '; Only commands with the rw flag are allowed to send database updates. Only',
  '; commands that have been verified to work in the Symphony environment should',
  '; have the rw keyword.',
].join('\n');

/** 是否为 ATM 生成段的行（用于幂等合并时剔除旧段） */
function isAtmMarkerLine(line: string): boolean {
  const trimmed = line.trim();
  return (
    trimmed.startsWith('; ===== ATM Generated Symphony Skill File') ||
    trimmed === SYMPHONY_ATM_MARKER_START ||
    trimmed === SYMPHONY_ATM_MARKER_END ||
    trimmed.includes('ATM Symphony 命令登记自动生成') ||
    trimmed.includes('Auto-generated by ATM')
  );
}

/** 去除行内注释（仅处理引号外的分号） */
function stripInlineComment(line: string): { code: string; comment: string | null } {
  let inQuote = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') inQuote = !inQuote;
    if (ch === ';' && !inQuote) {
      const comment = line.slice(i + 1).trim();
      return { code: line.slice(0, i), comment: comment || null };
    }
  }
  return { code: line, comment: null };
}

/** 解析单行命令登记 */
function parseCommandLine(line: string): { name: string; rw: boolean } | null {
  const { code } = stripInlineComment(line);
  const trimmed = code.trim();
  if (!trimmed) return null;

  // 格式1/2: "command name" [rw]（多词或带引号）
  const quoted = trimmed.match(/^"([^"]+)"\s*(rw)?$/i);
  if (quoted) {
    return { name: quoted[1].trim(), rw: Boolean(quoted[2]) };
  }

  // 格式3/4: command_name [rw]（无引号；容忍裸多词命令）
  const withRw = trimmed.match(/^(.*?)\s+rw\s*$/i);
  if (withRw && withRw[1].trim()) {
    return { name: withRw[1].trim(), rw: true };
  }

  return { name: trimmed, rw: false };
}

/**
 * 解析 symphony_skill.txt 内容
 */
export function parseSymphonySkillFile(content: string): SymphonySkillFileContent {
  const commands: SymphonyCommandEntry[] = [];
  const preservedLines: string[] = [];
  const lines = content.split(/\r?\n/);
  let isAtmGenerated = false;

  for (const line of lines) {
    if (isAtmMarkerLine(line)) {
      isAtmGenerated = true;
      continue; // ATM 段在重新生成时整体替换
    }

    const { code, comment } = stripInlineComment(line);
    const parsed = parseCommandLine(line);
    if (parsed) {
      commands.push({
        name: parsed.name,
        rw: parsed.rw,
        source: 'existing',
        comment: comment || undefined,
      });
    } else if (code.trim() || line.trim()) {
      // 保留注释/空行等非命令行（头部说明、空行结构）
      preservedLines.push(line);
    }
  }

  return { commands, preservedLines, isAtmGenerated };
}

/** 命令名输出格式化：含空格时加引号 */
export function formatCommandName(name: string): string {
  const trimmed = name.trim();
  return /\s/.test(trimmed) ? `"${trimmed}"` : trimmed;
}

/** 单条命令序列化 */
export function serializeCommandEntry(entry: SymphonyCommandEntry): string {
  const base = formatCommandName(entry.name);
  const suffix = entry.rw ? ' rw' : '';
  const comment = entry.comment ? ` ; ${entry.comment}` : '';
  return `${base}${suffix}${comment}`;
}

/**
 * 生成 symphony_skill.txt 完整内容
 *
 * 合并策略（应对 Cadence 连接时自动重建该文件）：
 *   - 输出官方模板说明头 + ATM 管理标记
 *   - ATM 命令段：按字母序输出，来源为 atm 的条目
 *   - 既有/手动段：保留解析出的 manual/existing 条目（去重、去 ATM 段）
 *   - 若 existingContent 已含 ATM 段，则旧 ATM 段整体被新段替换
 */
export function generateSymphonySkillContent(
  options: GenerateSymphonySkillOptions,
): string {
  const commands = options.commands || [];
  const existing = options.existingContent
    ? parseSymphonySkillFile(options.existingContent)
    : null;

  // 合并：ATM 命令（新）+ 既有手动/保留条目（去重，命令名大小写不敏感）
  const merged = new Map<string, SymphonyCommandEntry>();
  for (const cmd of commands) {
    const key = cmd.name.trim().toLowerCase();
    if (key && !merged.has(key)) merged.set(key, { ...cmd });
  }
  if (existing) {
    for (const cmd of existing.commands) {
      const key = cmd.name.trim().toLowerCase();
      if (!key) continue;
      if (!merged.has(key)) {
        merged.set(key, { ...cmd, source: 'existing' });
      } else {
        // 已存在同名：ATM 条目优先；若两者都是 rw，保留 rw
        const current = merged.get(key)!;
        if (cmd.rw) current.rw = true;
      }
    }
  }

  const atmCommands = [...merged.values()].sort((a, b) => a.name.localeCompare(b.name));

  const lines: string[] = [];
  lines.push(SYMPHONY_OFFICIAL_HEADER);
  lines.push(';');
  lines.push('; ===== ATM 管理说明 =====');
  lines.push('; 本文件由 ATM 自动生成（AllegroDevOpsTool）。');
  lines.push('; 手工添加的条目会在下次生成时保留；ATM 段会被整体替换。');
  lines.push(`; 生成时间: ${new Date().toISOString()}`);
  lines.push('');
  lines.push(SYMPHONY_ATM_MARKER_START);
  lines.push('; 以下命令由 ATM 按当前启用的 Skill 自动登记');
  lines.push('');

  if (atmCommands.length === 0) {
    lines.push('; (none)');
  } else {
    for (const cmd of atmCommands) {
      const withSkill = cmd.skillName
        ? { ...cmd, comment: cmd.comment ? `${cmd.comment} [${cmd.skillName}]` : `[${cmd.skillName}]` }
        : cmd;
      lines.push(serializeCommandEntry(withSkill));
    }
  }

  lines.push('');
  lines.push(SYMPHONY_ATM_MARKER_END);

  // 保留既有非 ATM 行（头部说明等），但剔除空段
  if (existing && existing.preservedLines.length > 0) {
    lines.push('');
    lines.push('; ===== 既有内容（保留） =====');
    lines.push(...existing.preservedLines);
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * 对比两份登记列表，返回差异摘要（用于 Apply Plan 描述）
 */
export function diffSymphonyCommands(
  before: SymphonyCommandEntry[],
  after: SymphonyCommandEntry[],
): { added: string[]; removed: string[]; rwChanged: string[] } {
  const beforeMap = new Map(before.map((c) => [c.name.trim().toLowerCase(), c]));
  const afterMap = new Map(after.map((c) => [c.name.trim().toLowerCase(), c]));
  const added: string[] = [];
  const removed: string[] = [];
  const rwChanged: string[] = [];

  for (const [key, cmd] of afterMap) {
    if (!beforeMap.has(key)) added.push(cmd.name);
  }
  for (const [key, cmd] of beforeMap) {
    if (!afterMap.has(key)) removed.push(cmd.name);
  }
  for (const [key, afterCmd] of afterMap) {
    const beforeCmd = beforeMap.get(key);
    if (beforeCmd && beforeCmd.rw !== afterCmd.rw) rwChanged.push(afterCmd.name);
  }
  return { added, removed, rwChanged };
}
